name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Runs on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "." # Deploys everything in the repo root
      - uses: actions/deploy-pages@v4
